### ISSUE TITLE
Creating a history note in Oriya as well as English

### ISSUE THREAD

**Issue by nehagoel2** [Intelehealth/Android-Mobile-Client#358]
Health workers make mistakes during data entry and they need to be able to review the final history note before they submit it to the doctor. Hence there needs to be a check point to be able to do that.

**Comment by amalafrozalam** [comment]
One proposed solution is to create a new column in the obs table. The column would just be titled with the language that is being used. Since the obs are referenced by their UUIDs, the language wouldn't really matter. However, this just isn't a really nice solution. The ultimate best solution is an offline translation engine that would take the generated english history note and turn it into Oriya.

**Comment by nehagoel2** [comment]
Moving out of this milestone, #359 is the stopgap solution for now
