### ISSUE TITLE
Bullet spacing should be implemented for visit summary

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#360]
When dealing with more than 1 complaint, the visit summary note at the end can become unwieldy and cluttered. This should be formatted a little nicer.

Proposed formatting:
"
**Complaint:** things and stuff
<new line>
<new line>
**Another complaint:** More things and such
"

**Comment by nehagoel2** [comment]
Take a look at how cluttered and hard to read a note is at the moment:

Abdominal Pain: Site - Upper (R) - Right Hypochondrium. Radiation - Pain radiates to - Right shoulder. Duration - since 1 Weeks. Character of the pain - Constant, Dull, aching. Severity - Severe, 7-9. , Vomiting, Fever, Decrease in appetite, chills chills, headache chills, headache, body ache chills , headache, body ache, dry cough, Nausea, Anorexia, Diarrhoea, Constipation, Abdominal distention / Bloating, Belching / Burping, Flatulence, Color change in stool [describe], Blood in stool, Change in frequency of urinating [describe], Color change in urine [describe], Hiccups, Restlessness, Injury - Exacerbating Factors - Coughing, resting on right side. Relieving Factors - None/Denied.

**Comment by dbarretto** [comment]
Cannot add new line characters as openmrs rest APIs does not accept it....
