### ISSUE TITLE
Editing the Visit note or precription from the openmrs doesn't reflect in the Visit Summary Screen. eg If doctor posted an medicine in prescribed medication mistaklenly, and deleted it from the openmrs, pressing the download button in the app doesn't reflects.

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/Android-Mobile-Client#410]

**Comment by nehagoel2** [comment]
Prithi - just to confirm. That means that after a doctor deletes a medication that it does not get deleted on the app side after hitting download from doctor?

Is this also happening for other things like advice, etc?

Can you also look into more aspects of this issue? Such as when the doctor is deleting the medicine is it being deleted from the database? We need to identify whether the issue is in the app's service not being able to update the information or the openMRS side where the information is not being updated.

**Comment by prithi69** [comment]
Its happening in other device also, when the doctor prescribe the medication mistakenly , and deletes it, it does not reflects back in the app, but it deletes from the databases also,
it reflects in the app when doctor prescribe the  medication again, replace the old medication which the doctor had prescribed mistakenly,
If the doctor prescribe it mistakenly and deletes it from the OpenMRS, and nothing prescribes after that, then the deleted medicine reflects in the app, it does not deleted automatically after pressing the download button.

**Comment by nehav39** [comment]
Branch: reverted-back
