### ISSUE TITLE
Change follow up date format

### ISSUE THREAD

**Issue by amalafrozalam** [Intelehealth/Android-Mobile-Client#459]
change format from mm/dd/yyyy to 24th April 2018

**Comment by prajwalhacker** [comment]
on which section on the app should these date format needs to be updated ?

**Comment by prajwalhacker** [comment]
the follow up date is being retrieved from the open mrs webpage and is being displayed on the app....so i order to change the follow up date format , the format has to be changed in the Open MRS webpage !

**Comment by nehagoel2** [comment]
Changed from mm/dd/yyyy to dd/mm/yyyy

**Comment by nehagoel2** [comment]
The date data is retrieved from the app local database - the change needs to be done only on the way the date is displayed on the app UI, not in the format it is stored in the local app db or the OpenMRS db. will have to write logic function to convert the date into dd-Month-yyyy from dd/mm/yyyy before displaying. This should be done for all dates in order to minimize confusion.

**Comment by nehagoel2** [comment]
Search Patient Activity - DOB in ListView
Active Patient Activity - DOB in ListView
Today's Patient Activity - DOB in ListView
Patient Detail Activity - DOB in CardView
Patient Detail Activity - VisitDate in CardView
VisitSummary Activity - Follow up date in CardView

**Comment by nehagoel2** [comment]
@amalafrozalam - how would we change this in the Node object in the date picker input types? 
We can just make the change to the String that goes into the final blurb of the Physical exam or the Complaint Note.

**Comment by amalafrozalam** [comment]
You would need to modify each of the alert dialogs that use a date picker type format. An example can be found on line 774 of the node object. The SimpleDateFormat would just need to be updated to the appropriate format.
