### ISSUE TITLE
Age calculation on entering date of birth is incorrect by a year

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#471]
Eg. If my date of birth is 1st July 1998. Then my age is 19 years 11 months. But the App calculates it to 20 years 11 months

**Comment by amalafrozalam** [comment]
Neha's testing on slack: Age calculation is not working in certain scenarios
Today's date: If I enter today's date - It shows -1 years
If I enter a date earlier than today's date - it shows -2 years
It should not accept a date older than the current date
If I put in a date 1 month ago, it shows -1 years, 1 month
If I put in a date 2 months ago, it shows -1 years, 2 months
If the date is in the current year - the year shows as -1 year instead of 0 years

**Comment by amalafrozalam** [comment]
[This section of the code is where the age calculation occurs.](https://github.com/Intelehealth/Android-Mobile-Client/blob/125cb51c5fef664065c1c37993b4997ba5af1a38/app/src/main/java/io/intelehealth/client/activities/identification_activity/IdentificationActivity.java#L393)

The code flow is as follows:
1. The user selects a date.
2. The selected date is stored as a calendar instance called dob
3. the SimpleDateFormat is set, to format the dates for later
4. the dobString is created by formatting the dob with the simpleDateFormat
5. years of age is calculated and stored in mAgeYears by subtracting the dob year from today's year (2018 - whatever the year was entered)
6. months of age is calculated and store in mAgeMonths by subtracting the dob month from today's month (07 - whatever was entered)
7. if mAgeMonths is less than 0, then 12 is added. this is to correct for situations where the month entered is before today's month (if today is july, but the month entered is november, then the math is 7 - 11, which is -4. If you add 12, then this is 8, which is correct)

**Necessary change**
After line 409, in that same if statement, if that condition occurs then mAgeYears should be subtracted by one. This will give the correct age.

Also minor change, Line 402 is not needed. It is already done on line 395
