### ISSUE TITLE
Check compatibility for kitkat

### ISSUE THREAD

**Issue by vibhabhirud** [Intelehealth/Android-Mobile-Client#567]
Health workers in the Philippines have Lenovo Tab 2A7-30GC
Display7.00-inch.
Processor1.3GHz quad-core.
Front Camera0.3-megapixel.
Resolution1024x600 pixels.
RAM1GB.
OSAndroid 4.4.
Storage16GB.

**Comment by AmbujPandey** [comment]
Current status: - multiDexVersion = '1.0.3', minSDKVersion 21
We are using Multidex, which support prior to Android 5.0 (API level 21) because our code contains 69166 methods in our project (which is more than 64K(65536)). 

To run our app on API level 19 we have to use ProductFlavors for our app.
[Click_here](https://developer.android.com/studio/build/multidex)
